# wrangler.toml
name = "security-guard-shift-scheduling-standard"
compatibility_date = "2025-10-28"
compatibility_flags = ["nodejs_compat"]

# Enable workers.dev subdomain
workers_dev = true

# Enable preview URLs
preview_urls = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# attach the Worker to your hostname
[[routes]]
pattern = "guardschedulator.kittawat.qzz.io"
custom_domain = true
