# wrangler.toml
name = "security-guard-shift-scheduling-standard"
compatibility_date = "2025-10-28"
compatibility_flags = ["nodejs_compat"]

# attach the Worker to your hostname
[[routes]]
pattern = "guardschedulator.kittawat.qzz.io"
custom_domain = true
