export const localeStrings={
  en:{
    languageLabel:'Language',
    languageEnglish:'English',
    languageThai:'Thai',
    themeLabel:'Theme',
    themeDark:'Dark',
    themeLight:'Light',
    headerTitle:'Enhanced Security Guard Scheduling',
    headerSubtitle:'Thailand calendar, role constraints, and editable rosters',
    testSetupTitle:'Test Setup',
    schedulePeriodLabel:'Schedule Period',
    timezoneLabel:'Timezone',
    countryLabel:'Country for Holidays',
    shiftPatternTitle:'Shift Pattern Registration',
    shiftNameHeader:'Shift Name',
    shiftNamePlaceholder:'Shift name',
    shiftMorningName:'Morning',
    shiftAfternoonName:'Afternoon',
    shiftNightName:'Night',
    startTimeHeader:'Start Time',
    shiftSizeHeader:'Size (hrs)',
    endTimeHeader:'End Time',
    guardNeededHeader:'Guard Roles Needed',
    supervisorNeededHeader:'Supervisor Roles Needed',
    seniorNeededHeader:'Senior Roles Needed',
    actionsHeader:'Actions',
    addShiftButton:'Add Shift',
    removeButton:'Remove',
    employeeConstraintsTitle:'Employee Constraints',
    maxWeeklyHoursLabel:'Max Weekly Hours per Employee',
    maxConsecutiveDaysLabel:'Max Consecutive Working Days',
    minDayOffLabel:'Minimum Full Day Off After Max Consecutive',
    maxContinuousHoursLabel:'Max Continuous Hours Per Day',
    employeeRosterTitle:'Employee Roster',
    employeeNameHeader:'Employee Name',
    employeeNamePlaceholder:'Employee name',
    roleHeader:'Role',
    maxHoursHeader:'Max Weekly Hours',
    unavailableDatesHeader:'Unavailable Dates',
    unavailRegisterTitle:'Unavailable Dates Register',
    unavailableDatesPanelHint:'(panel)',
    preferredShiftsHeader:'Preferred Shifts',
    preferredShiftsHint:'Multiple selections allowed. Options sync with global shift list.',
    spareHeader:'Spare',
    markAsSpare:'Mark as Spare',
    editButton:'Edit',
    addEmployeeButton:'Add Employee',
    employeeConfigTitle:'Employee Config',
    holidayRegisterTitle:'Holiday Register',
    holidayDateHeader:'Date',
    holidayNameHeader:'Name',
    holidayNamePlaceholder:'Holiday name',
    addHolidayButton:'Add Holiday',
    loadCountryDefaultsButton:'Load Country Defaults',
    clearAllButton:'Clear All',
    holidayHint:'Defaults come from selected country and are filterable by date range.',
    generateScheduleButton:'Generate Schedule',
    resultsTitle:'Schedule Results',
    constraintWeeklyHours:'Weekly Hours',
    constraintConsecutiveDays:'Consecutive Days',
    coverageRateTitle:'Coverage Rate',
    coverageRateSubtitle:'Staffing vs Requirement',
    roleComplianceTitle:'Role Compliance',
    roleComplianceSubtitle:'Role Requirements Met',
    constraintTitle:'Constraint Satisfaction',
    constraintSubtitle:'Rules Applied',
    processingTimeTitle:'Processing Time',
    processingTimeSubtitle:'Algorithm Execution',
    siteTab:'Site Schedule View',
    personalTab:'Personal Schedules',
    constraintTab:'Constraint Analysis',
    exportButton:'Export Schedule',
    exportFormatLabel:'Export format',
    exportFormatPdf:'PDF (print/save)',
    exportFormatHtml:'HTML',
    exportFormatJson:'JSON',
    exportFormatExcel:'Excel (.xls)',
    previewButton:'Preview',
    exportRequirementsHeader:'Requirements',
    exportAssignmentsHeader:'Assignments',
    popupBlockedMessage:'Unable to open preview window. Please allow pop-ups.',
    analysisWithinLimit:'Within limit',
    analysisExceedsLimit:'Exceeds limit',
    analysisDays:'days',
    analysisStreakTooLong:'Streak too long',
    analysisOk:'OK',
    analysisRestUnder:'Rest under {days} day(s)',
    analysisScheduledHours:'Scheduled Hours',
    analysisAllowedHours:'Allowed Hours',
    analysisStatus:'Status',
    analysisLongestStreak:'Longest Streak',
    analysisMaxAllowed:'Max Allowed',
    analysisStreakStatus:'Streak Status',
    analysisRestCompliance:'Rest Compliance',
    analysisHappiness:'Happiness',
    happinessLabel:'Happiness',
    happinessScore:'Happiness: {score}%',
    happinessUnknown:'Happiness cannot be calculated yet.',
    happinessPreferredSummary:'Preferred shifts {matched}/{total}',
    happinessWeekendSummary:'Weekend shifts {weekend}/{total}',
    happinessNightSummary:'Night shifts {night}/{total}',
    happinessFormulaHeading:'How happiness is calculated',
    happinessFormulaIntro:'Score starts at 100 and subtracts penalties:',
    happinessFormulaPreferred:'(1 - preferred match ratio) × 40',
    happinessFormulaWeekend:'Weekend ratio × 15',
    happinessFormulaNight:'Night shift ratio × 10',
    happinessFormulaHours:'If hours exceed limit: −15',
    happinessFormulaStreak:'If streak exceeds limit: −15',
    happinessFormulaRest:'If rest shorter than policy: −10',
    windowLabel:'Window',
    employeeLabel:'Employee',
    monthLabel:'Month',
    yearLabel:'Year',
    previous:'Previous',
    next:'Next',
    weekCounter:'Week {current} / {total}',
    noWeeks:'No weeks',
    noScheduleDays:'No schedule days available. Run the scheduler or adjust filters.',
    runSchedulerPrompt:'Run the scheduler to view the calendar.',
    noPersonalRoster:'Add employees to view personal schedules.',
    runSchedulerPersonal:'Run the scheduler to view personal schedules.',
    selectEmployeePrompt:'Select an employee to view the Gantt chart.',
    noDataInRange:'No schedule data within the selected range.',
    dayOffLabel:'Day Off',
    noShiftLabel:'No shift',
    noShiftsScheduled:'No shifts scheduled.',
    noShiftsConfigured:'No shifts configured for this day.',
    noShiftsDefined:'No shifts defined.',
    holidayEmptyRegister:'No public holidays configured.',
    noScheduleData:'No schedule data available.',
    noAssignmentsForDay:'No assignments for this day.',
    noAssignments:'No assignments',
    noAvailableEmployees:'No available employees',
    loadingHolidays:'Loading public holidays…',
    holidayNone:'No public holidays within selected period.',
    holidayErrorInvalidDates:'Enter valid schedule dates to load holidays.',
    holidayPromptSetRange:'Set a schedule period to load public holidays.',
    holidayLoadError:'Unable to load public holidays. Please try again later.',
    holidayLoadFallback:'Primary holiday service is unavailable. Holidays have been loaded from OpenHolidays.org.',
    holidayLoadFailure:'Unable to load public holidays from any online source. Please try again later.',
    errorFillRequired:'Please fill in all required fields.',
    errorDefineShift:'Define at least one shift pattern.',
    errorDefineEmployee:'Add at least one employee.',
    errorLockedShift:'This shift is locked and cannot be removed.',
    lockedLabel:'Locked',
    errorInvalidPeriod:'End date must be after start date.',
    errorShortShift:'Skipping shift shorter than minimum duration.',
    shiftStaffing:'Staff {assigned}/{required}',
    listNoStaff:'No staff assigned',
    noneLabel:'none',
    roleRequiredLabel:'Required: {count}',
    removeAssignmentAria:'Remove {name}',
    selectRolePlaceholder:'Select {role}',
    unsavedChanges:'Unsaved changes',
    addDateButton:'Add Date',
    closeButton:'Close',
    saveButton:'Save',
    discardButton:'Discard',
    addShiftLabel:'Add shift',
    addLabel:'Add',
    dayDetailTitle:'Day Detail',
    refillsDisabled:'Refills disabled; shortage remains',
    toolbarWeek:'Week',
    toolbarMonth:'Month',
    weekdayShort:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    weekdayLong:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
    monthNamesFull:['January','February','March','April','May','June','July','August','September','October','November','December'],
    roles:{ guard:'Guard', supervisor:'Supervisor', senior:'Senior Guard' }
  },
  th:{
    languageLabel:'ภาษา',
    languageEnglish:'อังกฤษ',
    languageThai:'ไทย',
    themeLabel:'โหมดสี',
    themeDark:'โหมดมืด',
    themeLight:'โหมดสว่าง',
    headerTitle:'ระบบจัดตารางเวรเจ้าหน้าที่รักษาความปลอดภัย',
    headerSubtitle:'ปฏิทินไทย กำหนดข้อจำกัดบทบาท และปรับตารางได้สะดวก',
    testSetupTitle:'การตั้งค่าทดสอบ',
    schedulePeriodLabel:'ช่วงเวลาตารางเวร',
    timezoneLabel:'เขตเวลา',
    countryLabel:'ประเทศสำหรับวันหยุด',
    shiftPatternTitle:'กำหนดรูปแบบกะ',
    shiftNameHeader:'ชื่อกะ',
    shiftNamePlaceholder:'ชื่อกะ',
    shiftMorningName:'กะเช้า',
    shiftAfternoonName:'กะบ่าย',
    shiftNightName:'กะกลางคืน',
    startTimeHeader:'เวลาเริ่ม',
    shiftSizeHeader:'ชั่วโมง',
    endTimeHeader:'เวลาสิ้นสุด',
    guardNeededHeader:'ต้องการเจ้าหน้าที่รักษาความปลอดภัย',
    supervisorNeededHeader:'ต้องการหัวหน้ากะ',
    seniorNeededHeader:'ต้องการเจ้าหน้าที่อาวุโส',
    actionsHeader:'ดำเนินการ',
    addShiftButton:'เพิ่มกะ',
    removeButton:'ลบ',
    employeeConstraintsTitle:'ข้อจำกัดพนักงาน',
    maxWeeklyHoursLabel:'ชั่วโมงทำงานสูงสุดต่อสัปดาห์',
    maxConsecutiveDaysLabel:'จำนวนวันทำงานต่อเนื่องสูงสุด',
    minDayOffLabel:'วันหยุดต่อเนื่องขั้นต่ำหลังทำงานเต็มจำนวน',
    maxContinuousHoursLabel:'ชั่วโมงทำงานต่อเนื่องสูงสุดต่อวัน',
    employeeRosterTitle:'รายชื่อพนักงาน',
    employeeNameHeader:'ชื่อพนักงาน',
    employeeNamePlaceholder:'ชื่อพนักงาน',
    roleHeader:'บทบาท',
    maxHoursHeader:'ชั่วโมงสูงสุดต่อสัปดาห์',
    unavailableDatesHeader:'วันที่ไม่ว่าง',
    unavailRegisterTitle:'ทะเบียนวันที่ไม่ว่าง',
    unavailableDatesPanelHint:'(แผง)',
    preferredShiftsHeader:'กะที่ต้องการ',
    preferredShiftsHint:'เลือกได้หลายรายการ ระบบซิงค์กับรายการกะหลัก',
    spareHeader:'สำรอง',
    markAsSpare:'ทำเครื่องหมายเป็นสำรอง',
    editButton:'แก้ไข',
    addEmployeeButton:'เพิ่มพนักงาน',
    employeeConfigTitle:'ตั้งค่าพนักงาน',
    holidayRegisterTitle:'รายการวันหยุด',
    holidayDateHeader:'วันที่',
    holidayNameHeader:'ชื่อ',
    holidayNamePlaceholder:'ชื่อวันหยุด',
    addHolidayButton:'เพิ่มวันหยุด',
    loadCountryDefaultsButton:'นำเข้าวันหยุดอ้างอิง',
    clearAllButton:'ล้างทั้งหมด',
    holidayHint:'ดึงจากประเทศที่เลือกและสามารถกรองตามช่วงวันที่ได้',
    generateScheduleButton:'สร้างตารางเวร',
    resultsTitle:'ผลลัพธ์ตารางเวร',
    constraintWeeklyHours:'ชั่วโมงต่อสัปดาห์',
    constraintConsecutiveDays:'จำนวนวันทำงานต่อเนื่อง',
    coverageRateTitle:'อัตราครอบคลุม',
    coverageRateSubtitle:'พนักงานเทียบกับความต้องการ',
    roleComplianceTitle:'ความครบถ้วนตามบทบาท',
    roleComplianceSubtitle:'ตรงตามบทบาทที่ต้องการ',
    constraintTitle:'การปฏิบัติตามข้อจำกัด',
    constraintSubtitle:'กฎที่ใช้',
    processingTimeTitle:'เวลาประมวลผล',
    processingTimeSubtitle:'เวลาทำงานของอัลกอริทึม',
    siteTab:'ตารางเวรหน้างาน',
    personalTab:'ตารางเวรบุคคล',
    constraintTab:'วิเคราะห์ข้อจำกัด',
    exportButton:'ส่งออกตาราง',
    exportFormatLabel:'รูปแบบไฟล์',
    exportFormatPdf:'PDF (พิมพ์/บันทึก)',
    exportFormatHtml:'HTML',
    exportFormatJson:'JSON',
    exportFormatExcel:'Excel (.xls)',
    previewButton:'ดูตัวอย่าง',
    exportRequirementsHeader:'ความต้องการ',
    exportAssignmentsHeader:'การมอบหมาย',
    popupBlockedMessage:'ไม่สามารถเปิดหน้าต่างดูตัวอย่างได้ โปรดอนุญาตป๊อปอัป',
    analysisWithinLimit:'อยู่ในเกณฑ์',
    analysisExceedsLimit:'เกินเกณฑ์',
    analysisDays:'วัน',
    analysisStreakTooLong:'ทำงานต่อเนื่องนานเกินไป',
    analysisOk:'ปกติ',
    analysisRestUnder:'พักไม่ถึง {days} วัน',
    analysisScheduledHours:'ชั่วโมงที่จัดตาราง',
    analysisAllowedHours:'ชั่วโมงที่อนุญาต',
    analysisStatus:'สถานะ',
    analysisLongestStreak:'ทำงานต่อเนื่องยาวสุด',
    analysisMaxAllowed:'เพดานที่อนุญาต',
    analysisStreakStatus:'สถานะการทำงานต่อเนื่อง',
    analysisRestCompliance:'สถานะการพัก',
    analysisHappiness:'ความสุข',
    happinessLabel:'ความสุข',
    happinessScore:'ความสุข: {score}%',
    happinessUnknown:'ยังไม่สามารถคำนวณค่าความสุขได้',
    happinessPreferredSummary:'กะที่ต้องการ {matched}/{total}',
    happinessWeekendSummary:'กะเสาร์อาทิตย์ {weekend}/{total}',
    happinessNightSummary:'กะกลางคืน {night}/{total}',
    happinessFormulaHeading:'สูตรการคำนวณความสุข',
    happinessFormulaIntro:'เริ่มต้นที่ 100 และหักค่าปรับดังนี้:',
    happinessFormulaPreferred:'(1 - สัดส่วนกะที่ต้องการ) × 40',
    happinessFormulaWeekend:'สัดส่วนกะเสาร์อาทิตย์ × 15',
    happinessFormulaNight:'สัดส่วนกะกลางคืน × 10',
    happinessFormulaHours:'หากชั่วโมงเกินเกณฑ์: −15',
    happinessFormulaStreak:'หากทำงานต่อเนื่องเกินกำหนด: −15',
    happinessFormulaRest:'หากวันพักน้อยกว่าเกณฑ์: −10',
    windowLabel:'ช่วงมุมมอง',
    employeeLabel:'พนักงาน',
    monthLabel:'เดือน',
    yearLabel:'ปี',
    previous:'ก่อนหน้า',
    next:'ถัดไป',
    weekCounter:'สัปดาห์ {current} / {total}',
    noWeeks:'ไม่มีข้อมูลสัปดาห์',
    noScheduleDays:'ไม่มีข้อมูลตารางในช่วงนี้ โปรดสร้างตารางใหม่หรือปรับตัวกรอง',
    runSchedulerPrompt:'สร้างตารางเพื่อแสดงปฏิทิน',
    noPersonalRoster:'เพิ่มพนักงานเพื่อดูตารางบุคคล',
    runSchedulerPersonal:'สร้างตารางเพื่อดูตารางบุคคล',
    selectEmployeePrompt:'เลือกพนักงานเพื่อดูแผนผังกะ',
    noDataInRange:'ไม่มีข้อมูลในช่วงที่เลือก',
    dayOffLabel:'วันหยุด',
    noShiftLabel:'ไม่มีเวร',
    noShiftsScheduled:'ไม่มีการจัดเวร',
    noShiftsConfigured:'ยังไม่ได้กำหนดเวรสำหรับวันนี้',
    noShiftsDefined:'ยังไม่ได้กำหนดรูปแบบกะ',
    holidayEmptyRegister:'ไม่มีวันหยุดในรายการ',
    noScheduleData:'ไม่มีข้อมูลตารางในระบบ',
    noAssignmentsForDay:'ไม่มีการมอบหมายในวันนี้',
    noAssignments:'ไม่ได้จัดพนักงาน',
    noAvailableEmployees:'ไม่มีพนักงานว่าง',
    loadingHolidays:'กำลังโหลดวันหยุด…',
    holidayNone:'ไม่มีวันหยุดในช่วงวันที่เลือก',
    holidayErrorInvalidDates:'กรุณาระบุวันที่เริ่มและสิ้นสุดให้ถูกต้อง',
    holidayPromptSetRange:'กรุณากำหนดช่วงวันที่เพื่อโหลดวันหยุด',
    holidayLoadError:'ไม่สามารถโหลดวันหยุด โปรดลองอีกครั้ง',
    holidayLoadFallback:'ไม่สามารถใช้บริการหลัก จึงใช้ข้อมูลจาก OpenHolidays.org',
    holidayLoadFailure:'ไม่สามารถโหลดวันหยุดจากแหล่งข้อมูลออนไลน์ได้',
    errorFillRequired:'กรุณากรอกข้อมูลที่จำเป็นให้ครบ',
    errorDefineShift:'กรุณากำหนดรูปแบบกะอย่างน้อยหนึ่งรายการ',
    errorDefineEmployee:'กรุณาเพิ่มพนักงานอย่างน้อยหนึ่งคน',
    errorLockedShift:'ไม่สามารถลบกะที่ถูกล็อกได้',
    lockedLabel:'ล็อก',
    errorInvalidPeriod:'วันสิ้นสุดต้องอยู่หลังวันเริ่มต้น',
    errorShortShift:'ข้ามกะที่มีระยะเวลาสั้นเกินไป',
    shiftStaffing:'พนักงาน {assigned}/{required}',
    listNoStaff:'ไม่มีพนักงานในกะนี้',
    noneLabel:'ไม่มี',
    roleRequiredLabel:'ต้องการ: {count}',
    removeAssignmentAria:'ลบ {name}',
    selectRolePlaceholder:'เลือก{role}',
    unsavedChanges:'มีการแก้ไขค้างอยู่',
    addDateButton:'เพิ่มวันที่',
    closeButton:'ปิด',
    saveButton:'บันทึก',
    discardButton:'ยกเลิก',
    addShiftLabel:'เพิ่มกะ',
    addLabel:'เพิ่ม',
    dayDetailTitle:'รายละเอียดกะ',
    refillsDisabled:'ปิดการเติมกะอัตโนมัติ ความขาดแคลนยังคงอยู่',
    toolbarWeek:'รายสัปดาห์',
    toolbarMonth:'รายเดือน',
    weekdayShort:['อา','จ','อ','พ','พฤ','ศ','ส'],
    weekdayLong:['วันอาทิตย์','วันจันทร์','วันอังคาร','วันพุธ','วันพฤหัสบดี','วันศุกร์','วันเสาร์'],
    monthNamesFull:['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'],
    roles:{ guard:'เจ้าหน้าที่รักษาความปลอดภัย', supervisor:'หัวหน้ากะ', senior:'เจ้าหน้าที่อาวุโส' }
  }
};
